apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: soneta
  namespace: argocd
spec:
  project: default
  source:
    chart: soneta
    repoURL: 'https://github.com/soneta/helm-charts/tree/main/charts/soneta'
    targetRevision: main
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: soneta
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true